version: '2.0'

# This only spins up the Postgres.
# Run the Java app locally as normal

services:
#  web:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  swagger-ui:
    image: swaggerapi/swagger-ui:v3.0.17
    ports:
      - '8090:8080'

 # openam:
 #   build:
 #     context: 'docker/openam'
 #   ports:
 #     - '4000:8080'

  # Use for deployment from IDE, mutually exclusive with building web
#   wildfly:
#     build:
#       context: ./docker/wildfly-admin
#     ports:
#       - "8787:8787"
#       - "8080:8080"
#       - "9990:9990"

#  zipkin:
#    image: openzipkin/zipkin:latest
#    ports:
#      - "9411:9411"


  jaegar:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"

volumes:
  postgres:
